import "@/styles/globals.css"; //this file CANNOT be imported in a different file
import "bootstrap/dist/css/bootstrap.min.css"; //if you wann use Bootstrap do this import here
import type { AppProps } from "next/app";
import { Inter } from "next/font/google";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className={`${inter.className}`}>
      <Head>
        <title key="title">My NextApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>...and also this one</p>
      <Component {...pageProps} />
    </div>
  );
}
